Ace\UserBundle\Entity\User:
    properties:
        username:
            - MinLength: { limit: 3, message: "Your Username needs to be at least 3 characters long." }
        plainPassword:
            - MinLength: { limit: 6, message: "Your Password needs to be at least 6 characters long." }
            - MaxLength: { limit: 255, message: "Your Password cannot be longer than 255 characters." }
            - Ace\UserBundle\Validator\Constraints\PasswordConstraint: ~                   
