parameters:
#    ace_project.example.class: Ace\ProjectBundle\Example

services:
#    ace_project.example:
#        class: %ace_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ace_project.diskfilecontroller:
        class:        Ace\ProjectBundle\Controller\DiskFilesController
        arguments:
            directory:    "%disk.directory%"

    ace_project.mongofilecontroller:
        class:        Ace\ProjectBundle\Controller\MongoFilesController
        arguments:
            documentManager: "@doctrine.odm.mongodb.document_manager"

    ace_project.projectmanager:
        class:        Ace\ProjectBundle\Controller\ProjectsController
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            mongofilecontroller: "@ace_project.mongofilecontroller"
            diskfilecontroller: "@ace_project.diskfilecontroller"
            storagelayer: "%storagelayer%"
